### ISSUE TITLE
Crash: node_data->_claimed_items.has_any()

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#101]
**Callstack (if a crash)**
13.03.2021
---------------------------
tdtd: The game has crashed.
---------------------------
Error: 
Hammerting version 0.2.1.6
Save version: version 0.2.1.0,version 0.2.1.4,version 0.2.1.5,version 0.2.1.6
Callstack:
0: bt_haul_update
tdtd\gamestate\behavior_trees\node_haul.cpp:817:55
1: ai_behavior_system_update
tdtd\gamestate\systems\ai_behavior_system.cpp:331:0
2: entity_entity_manager_update
entity\entity_manager.cpp:183:0
3: gamestate::update
tdtd\gamestate\gamestate.cpp:634:0
4: main_main_h::update
tdtd\main\main.cpp:561:0
5: game_func
tdtd\main\main.cpp:935:0
6: thread_entry
wc_sys\thread.cpp:104:0
7: configthreadlocale
8: BaseThreadInitThunk
9: RtlUserThreadStart

Assertion failed: node_data->_claimed_items.has_any()
File: c:/buildbot/build_tdtd-patch-windows-dev/warpcore/tdtd/gamestate/behavior_trees/node_haul.cpp
Line: 817

**Additional context**
From player e-mail

**Comment by Hericage** [comment]
Fixed one cause for this assert. It could potentially happen in other ways but the most common case should be fixed (trade claims on items being hauled by a dwarf did not behave well when saving/loading).
Also added some more information to the assert.
