### ISSUE TITLE
Crash: sys_strlen

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#114]
**Callstack (if a crash)**
---------------------------
Exception caught
---------------------------
Hammerting version 0.2.1.15
Save version: version 0.2.1.15
0:
ExceptionCode:
0xc0000005
ExceptionFlags:
0x0
ExceptionAddress:
0x7ffa8817f04a
Module:
E:\Games\SteamLibrary\steamapps\common\Hammerting\game.x86_64.dll

Callstack:
0: sys_strlen
wc_sys\public\wc_sys\sysinc.h:114:10
1: wc_hash_string
wc_sys\public\wc_sys\sysinc.h:528:14
2: `register_property_string'::`2'::<lambda_2>::operator()
core\property\string.h:34:13
3: resolve_hash_chain
entity\systems\property_component_system.cpp:343:0
4: property_component_system_evaluate_chain_args
entity\systems\property_component_system.cpp:931:88
5: property_component_system_evaluate_chain_args
entity\public\entity\entity.gen.h:349:115
6: set_property_default
ui\default_input_response.cpp:40:0
7: ui_button_internal_set_property
ui\default_input_response.cpp:159:0
8: trigger_response
ui\input_component_system.cpp:457:14
9: input_component_system_process_input
ui\input_component_system.cpp:810:0
10: input_component_system_process_input_wrapper_locked
tdtd\media\gamegfx_base.cpp:504:0
11: gamegfx_base::handle_message
tdtd\media\gamegfx_base.cpp:2948:34
12: gamegfx_handle_message
tdtd\media\gamegfx.cpp:2788:0
13: gfx_func
media\gfx.cpp:243:13
14: thread_entry
wc_sys\thread.cpp:109:0
15: configthreadlocale
16: BaseThreadInitThunk
17: RtlUserThreadStart

**Additional context**
From support email, KE

**Comment by fredrikz** [comment]
Can't get any information from this callstack sadly, will make sure to add some additional features when getting a nullptr crash
