### ISSUE TITLE
Crash: order_move_on_entities_destroyed

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#116]
**Callstack (if a crash)**
---------------------------
Exception caught
---------------------------
Hammerting version 0.2.1.15
0:
ExceptionCode:
0xc0000005
ExceptionFlags:
0x0
ExceptionAddress:
0x7ffa7661a644
Module:
E:\Games\SteamLibrary\steamapps\common\Hammerting\game.x86_64.dll

Callstack:
0: order_move_on_entities_destroyed
tdtd\gamestate\orders\order_move_to.cpp:99:16
1: order_system_remove_destroyed_entities
tdtd\gamestate\systems\order_system.cpp:182:30
2: entity_entity_manager_commit_pending
entity\entity_manager.cpp:146:15
3: gamestate::update
tdtd\gamestate\gamestate.cpp:636:0
4: main_main_h::update
tdtd\main\main.cpp:562:0
5: game_func
tdtd\main\main.cpp:935:0
6: thread_entry
wc_sys\thread.cpp:109:0
7: configthreadlocale
8: BaseThreadInitThunk
9: RtlUserThreadStart

**Describe the bug**
Game stuttered then crashed

**Additional context**
From support e-mail, KE

**Comment by fredrikz** [comment]
Fixed in 0.4.0.22
