### ISSUE TITLE
Crash: /warpcore/ui/font_component_system.cpp

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#122]
**Callstack (if a crash)**
Hammerting version 0.2.1.15
Save version: version 0.2.1.16,version 0.2.1.15

Callstack:
0: `anonymous namespace'::validate_texts
ui\font_component_system.cpp:1468:36
1: `anonymous namespace'::font_component_system::set_text
ui\font_component_system.cpp:1588:14
2: font_component_system_set_entity_texts
ui\font_component_system.cpp:2071:45
3: font_component_system_set_entity_text
ui\font_component_system.cpp:2057:0
4: warpcore::debuginator_ui::draw_text
tdtd\media\ui\debuginator_ui.cpp:640:0
5: warpcore::draw_text_wrapper
tdtd\media\ui\debuginator_ui.cpp:97:0
6: debuginator__draw_tooltip
single_header_libs\the_debuginator.h:3690:39
7: debuginator_draw
single_header_libs\the_debuginator.h:3374:0
8: warpcore::debuginator_ui::update
tdtd\media\ui\debuginator_ui.cpp:282:11
9: gamegfx_render
tdtd\media\gamegfx.cpp:997:0
10: gfx::render
media\gfx.cpp:153:0
11: gfx_func
media\gfx.cpp:257:0
12: thread_entry
wc_sys\thread.cpp:109:0
13: configthreadlocale
14: BaseThreadInitThunk
15: RtlUserThreadStart

Assertion failed: !"No"

File: c:/buildbot/build_tdtd-patch-windows-dev/warpcore/ui/font_component_system.cpp
Line: 1467

**Describe the bug**
 Overall I think that UI is causing some issues in the current experimental build - whenever some window pops up (like dwarf selection, etc.), there's a massive, short fps drop. 

**Additional context**
From support e-mail, LJ

**Comment by fredrikz** [comment]
Fixed in 0.4.0.22
