### ISSUE TITLE
Crash: > order_move_on_entities_destroyed

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#123]
**Callstack (if a crash)**
>	game.x86_64.dll!order_move_on_entities_destroyed(order * o, const unsigned short * entities, unsigned __int64 num_entities, gamestate * gs) Line 96	C++
 	game.x86_64.dll!order_system_remove_destroyed_entities(entity_component_system * ecs, const unsigned short * entities, unsigned __int64 num_entities, fixedpoint<__int64,16> time_now) Line 182	C++
 	entity.x86_64.dll!entity_entity_manager_commit_pending(entity_entity_manager_h * manager, fixedpoint<__int64,16> time_now) Line 147	C++
 	entity.x86_64.dll!entity_entity_manager_update(entity_entity_manager_h * manager, double dt, fixedpoint<__int64,16> time_now) Line 187	C++
 	game.x86_64.dll!entity_manager::update(double dt, fixedpoint<__int64,16> time_now) Line 1440	C++
 	game.x86_64.dll!gamestate::update(double delta, fixedpoint<__int64,16> time_now, double real_delta) Line 661	C++
 	game.x86_64.dll!main_main_h::update(double delta, fixedpoint<__int64,16> time_now, double real_delta) Line 562	C++
 	game.x86_64.dll!game_func(void * is_main_thread) Line 934	C++
 	wc_sys.dll!thread_entry(void * arg) Line 100	C++
 	[External Code]	

**Describe the bug**
Could be related to elevators

**Additional context**
From support e-mail, related to this thread probably: https://steamcommunity.com/app/760650/discussions/0/2999925317375748862/
FR

**Comment by fredrikz** [comment]
Fixed inm 0.4.0.22
