### ISSUE TITLE
Crash: Position list contains duplicates. This will probably cause problems and confuse the workers

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#124]
**Callstack (if a crash)**
[00:04:01.607918|Hammerting version 0.3.0.0|c:/users/linda/repo/warpcore/tdtd/gamestate/systems/job_broker_system.cpp:850] ASSERT failed: !positions[i].is_same_pos( positions[j] ) [Position list contains duplicates. This will probably cause problems and confuse the workers.

Hammerting version 0.3.0.0

Callstack:
0: job_broker_system::set_workplace_positions
tdtd\gamestate\systems\job_broker_system.cpp:850:124
1: job_broker_system_set_workplace_positions
tdtd\gamestate\systems\job_broker_system.cpp:2465:0
2: refresh_dig_site
tdtd\gamestate\sensors\sensor_dig.cpp:1006:0
3: update_dig_sites
tdtd\gamestate\sensors\sensor_dig.cpp:1300:0
4: sensor_dig_update
tdtd\gamestate\sensors\sensor_dig.cpp:1320:0
5: sensor_system_update
tdtd\gamestate\systems\sensor_system.cpp:210:0
6: entity_entity_manager_update
entity\entity_manager.cpp:184:0
7: entity_manager::update
entity\public\entity\entity.gen.h:1440:0
8: gamestate::update
tdtd\gamestate\gamestate.cpp:660:0
9: main_main_h::update
tdtd\main\main.cpp:562:0
10: game_func
tdtd\main\main.cpp:934:36
11: thread_entry
wc_sys\thread.cpp:100:19
12: configthreadlocale
13: BaseThreadInitThunk
14: RtlUserThreadStart

**Describe the bug**
Related to melding of dig sites. "borde nog vara en push_unique nånstans istället för push"

**Additional context**
Mine.

**Comment by Srekel** [comment]
Fixed in 0.3.0.1
