### ISSUE TITLE
Biome effects don't get removed properly

### ISSUE THREAD

**Issue by Srekel** [WarpzoneStudios/Hammerting#125]
![image](https://user-images.githubusercontent.com/1578924/114996834-86978e00-9e9f-11eb-9942-6d289a76ce2c.png)

https://discord.com/channels/346642400497762305/722523504108503091/832532978969870347

**Comment by ForzaA84** [comment]
To repro from save (save & load appears to reset the issue)
1) Select Viglek Blekhammar
2) Send them down to the bottom(left) [illustrative screenshot added]
3) once they get there, detailed tooltip for Vision Range should be as above (give or take - may depend on exact pathing)

[c13.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/6323667/c13.2.save.zip)
![ToTheMines](https://user-images.githubusercontent.com/82644410/114997721-72a05c00-9ea0-11eb-9d51-2e3b07139794.png)

**Comment by Srekel** [comment]
Fixed in 0.3.0.9
