### ISSUE TITLE
Skeletons stuck and cannot climb stair-style ground

### ISSUE THREAD

**Issue by chabbrik** [WarpzoneStudios/Hammerting#13]
**Describe the bug**
Skeletons stuck and cannot climb stair-style ground

**To Reproduce**
Load the game and watch them move.

**Expected behavior**
Skeletons can move towards my base

**Comment by chabbrik** [comment]
[Stuck skeletons.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/5964026/Stuck.skeletons.2.save.zip)

**Comment by Srekel** [comment]
I believe this is fixed in 0.2.0.0. Please reopen if it persists. :)
