### ISSUE TITLE
Crash: TDTD_EVENT_ANIM_START

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#137]
**Callstack (if a crash)**
Hammerting version 0.3.0.15
Save version: version 0.3.0.15

Additional assert messages:
TDTD_EVENT_ANIM_START

Callstack:
0: haul_claim_ref::from_u64
tdtd\gamestate\public\gamestate\game_entity_types.h:2059:75
1: add_haulable_items
tdtd\gamestate\systems\haul_system.cpp:1056:0
2: add_item_entity
tdtd\gamestate\systems\haul_system.cpp:259:27
3: haul_system_create_components
tdtd\gamestate\systems\haul_system.cpp:296:0
4: entity_entity_manager_create_entities
entity\entity_manager.cpp:521:15
5: entity_entity_manager_create_entity
entity\entity_manager.cpp:303:0
6: default_production_complete_cbck
tdtd\gamestate\craft_util.cpp:296:0
7: production_system_modify_progress
tdtd\gamestate\systems\production_system.cpp:1151:22
8: event_callback_anim
tdtd\gamestate\behavior_trees\node_produce.cpp:123:0
9: event_component_system_trigger_event_hash_internal
entity\systems\event_component_system.cpp:345:15
10: event_component_system_trigger_event_hash
entity\systems\event_component_system.cpp:389:0
11: game_animation_system_update
tdtd\gamestate\systems\game_animation_system.cpp:447:0
12: entity_entity_manager_update
entity\entity_manager.cpp:183:12
13: gamestate::update
tdtd\gamestate\gamestate.cpp:680:0
14: main_main_h::update
tdtd\main\main.cpp:562:0
15: game_func
tdtd\main\main.cpp:942:0
16: thread_entry
wc_sys\thread.cpp:109:0
17: configthreadlocale
18: BaseThreadInitThunk
19: RtlUserThreadStart

Assertion failed: _item_entity != 0

File: C:\buildbot\build_tdtd-patch-windows-dev\warpcore\tdtd\gamestate\public\gamestate\game_entity_types.h
Line: 2059

**Describe the bug**
This was fixed once. Not fixed enough, or is it back?

**Additional context**
From support e-mail, KE

**Comment by fredrikz** [comment]
Fixed in 0.4.0.22
