### ISSUE TITLE
Drill animation is not working after reloading game

### ISSUE THREAD

**Issue by chabbrik** [WarpzoneStudios/Hammerting#14]
**Describe the bug**
Crusher drill animation does not work on load, though it is still mining stuff

**To Reproduce**
Build a crusher drill, save game and reload. 

**Expected behavior**
Drill animation should work when loading the game.

[Buggy drills.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/5964038/Buggy.drills.2.save.zip)

**Comment by Makishima** [comment]
still on  0.2.0.5

**Comment by Syfrex** [comment]
Fixed in 0.2.1.0
