### ISSUE TITLE
Sorting by Price, Name in Overworld doesn't work

### ISSUE THREAD

**Issue by CamelKnight** [WarpzoneStudios/Hammerting#144]
**Describe the bug**
Sorting by Price or Name or any other sorting option in Overworld doesn't work

**To Reproduce**
1. Go to Overworld
2. Select a Town
3. Click Price button
4. Nothing happens

**Expected behavior**
When clicking the Price button, I'd expect the prices to be sorted by high to low/low to high, but nothing happens. 

**Screenshots**
x

**Desktop (please complete the following information if pertinent):**
 - Graphics Card
 - Game Version [e.g. 22]

**Additional context**
x

**Comment by fredrikz** [comment]
Fixed in 0.4.0.22
