### ISSUE TITLE
Crash: ASSERT failed: _total [

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#151]
**Callstack (if a crash)**
 	game.x86_64.dll!weighted_random<unsigned int,fixedpoint<int,16>>::set_data(const fixedpoint<int,16> * data, unsigned __int64 data_count, unsigned __int64 offset) Line 151	C++
>	game.x86_64.dll!run_owloc_production_logic(overworld_location_system * system, overworld_location_component * lc, bool reinitialize) Line 275	C++
 	game.x86_64.dll!update_local_market(overworld_location_system * system, overworld_location_component * lc, fixedpoint<__int64,16> time_now) Line 441	C++
 	game.x86_64.dll!overworld_location_system_update(entity_component_system * ecs, double dt, fixedpoint<__int64,16> time_now) Line 481	C++
 	entity.x86_64.dll!entity_entity_manager_update(entity_entity_manager_h * manager, double dt, fixedpoint<__int64,16> time_now) Line 184	C++
 	game.x86_64.dll!entity_manager::update(double dt, fixedpoint<__int64,16> time_now) Line 1485	C++
 	game.x86_64.dll!gamestate::update(double delta, fixedpoint<__int64,16> time_now, double real_delta) Line 679	C++
 	game.x86_64.dll!main_main_h::update(double delta, fixedpoint<__int64,16> time_now, double real_delta) Line 567	C++
 	game.x86_64.dll!game_func(void * is_main_thread) Line 959	C++
 	wc_sys.dll!thread_entry(void * arg) Line 100	C++

**Describe the bug**
Item spawning with weight 0 % chance.

**To Reproduce**
1. Load attached save
2. Let the game run for a minute or so.

**Additional context**
From support e-mail B L D
[savegame61.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/6596633/savegame61.2.save.zip)

**Comment by fredrikz** [comment]
Fixed
