### ISSUE TITLE
Water(and possibly lava) does not start flowing when it should

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#16]
**Describe the bug**
When a block is dug near water the water does not start flowing when it can/should

**To Reproduce**
1. Go to a water source
2. Dig a block next to/ under the source
3. Water does not flow down or to the side

**Expected behavior**
Water should start flowing to the open space when it is created

**Screenshots**

![](https://cdn.discordapp.com/attachments/771649477601525763/809745904525377566/unknown.png)

![](https://cdn.discordapp.com/attachments/771649477601525763/809746576254828554/unknown.png)

![](https://cdn.discordapp.com/attachments/771649477601525763/809747054166540318/unknown.png)

https://discord.com/channels/346642400497762305/771649477601525763/809746291458048030

**Comment by fredrikz** [comment]
Fixed in 0.2.0.1
