### ISSUE TITLE
Sacred Well Inventorry Accessability

### ISSUE THREAD

**Issue by Gerydos** [WarpzoneStudios/Hammerting#18]
**Describe the bug**
My dwarfs can't empty the inventory of the Sacred Well. I've set up a Storage Chest and a Storage Building with high priority and the dwarfs doesn't want to take the water from the well. But they'll rush for it when i drop it from the Well's inventory.
Furthermore i can sell the Sacred Water directly from the well and they can get to it and transfer it.

**To Reproduce**
Craft some water and try to stockpile it.

**Expected behavior**
Being able to get the Sacred Water and stockpile it for use.

**Desktop (please complete the following information if pertinent):**
 - OS: Windows
 - Sapprihe R9 290
 - Game Version 0.2.0.0
 
 **Suggestion**
 An empty the whole inventory button would be nice in all buildings. We could use it as a workaround in case for any similiar bugs.

**Comment by Gerydos** [comment]
**Edited:**
I had to correct the name for "Sacred Water" from simple Water
I've also added a suggestion

**Comment by Srekel** [comment]
https://discord.com/channels/346642400497762305/771649477601525763/809815568278224897

**Comment by Gerydos** [comment]
Fixed in 0.2.0.3

Thanks!
