### ISSUE TITLE
Unable to select what material to use.

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#22]
**Describe the bug**
I can not open the menu in which to choose what metal to use to craft something
**To Reproduce**
1. Go to smithy
2. Click on the menu to choose the material.(it does not matter which part you choose)
3. Observe that it does not open.

**Expected behavior**
It should open and let me choose what material to use.

**Screenshots**
https://discord.com/channels/346642400497762305/771649477601525763/809838134158295050

Game version exp. 0.2.0.1

**Comment by Gerydos** [comment]
I have the same issue aswell.

**Comment by Srekel** [comment]
Fixed in 0.2.0.3
