### ISSUE TITLE
Brewing has too many things going on

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#23]
**Describe the bug**
Check mark overlaps with items in Brewing knowledge

**Expected behavior**
It should not overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/78851197/107801984-11092780-6d61-11eb-91a0-6d5a178be6c6.png)

**Comment by Srekel** [comment]
Fixed in 0.2.0.2
