### ISSUE TITLE
I can place bridges in lava

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#24]
**Describe the bug**
I'm able to place a stone bridge inside a lake of lava without it disappearing.

**Expected behavior**
When placing solid blocks/items the lava should despawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/78851197/107819576-afa18280-6d79-11eb-8d78-8cece49373a3.png)

**Comment by fredrikz** [comment]
Fixed in 0.2.0.4
