### ISSUE TITLE
Dwarves will refill buildings even if full

### ISSUE THREAD

**Issue by Srekel** [WarpzoneStudios/Hammerting#26]
> 
> dwarves will refill buildings (like smelter, forge, bore) several times in a row even if its  already full
> eventually they completely waste all coal

https://discord.com/channels/346642400497762305/771649477601525763/809800168840757259

**Comment by Srekel** [comment]
[bug_coal_refill.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/5975711/bug_coal_refill.2.save.zip)

Happens fairly soon after there. Seems easy to repro, 1000/1000 foundry, still dwarf chooses to refill.

**Comment by Hericage** [comment]
Fixed in internal build.
Buildings that did not need anything were not updated, causing their refuel-jobs to stay active even when not needed.
