### ISSUE TITLE
Assertion failed: fp_from >= 0

### ISSUE THREAD

**Issue by fredrikz** [WarpzoneStudios/Hammerting#27]
**Callstack (if a crash)**
0: fixed_point_cast<fixedpoint<int,16>,fixedpoint<__int64,16> >
core\fixedpoint.h:176:71
1: add_experience
tdtd\gamestate\public\gamestate\xp_level.h:226:14
2: add_experience_and_announce
tdtd\gamestate\public\gamestate\xp_level.h:288:0
3: event_callback_anim
tdtd\gamestate\behavior_trees\node_produce.cpp:117:0
4: event_component_system_trigger_event_hash_internal
entity\systems\event_component_system.cpp:343:15
5: event_component_system_trigger_event_hash
entity\systems\event_component_system.cpp:387:0
6: game_animation_system_update
tdtd\gamestate\systems\game_animation_system.cpp:437:0
7: entity_entity_manager_update
entity\entity_manager.cpp:183:0
8: gamestate::update
tdtd\gamestate\gamestate.cpp:626:0
9: main_main_h::update
tdtd\main\main.cpp:561:0
10: game_func
tdtd\main\main.cpp:917:0
11: thread_entry
wc_sys\thread.cpp:104:0
12: configthreadlocale
13: BaseThreadInitThunk
14: RtlUserThreadStart

**Describe the bug**

**To Reproduce**
To reproduce  this issue:
1. Remove the Brewery
2. Give the order to rebuilt it
3. Wait a bit for the crash

[dreton.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/5975646/dreton.2.save.zip)

**Comment by Gerydos** [comment]
![20210213140027_1](https://user-images.githubusercontent.com/78972553/107850625-110e3380-6e04-11eb-8d40-4060a23767f2.jpg)

Possible cause of the issue. My dwars are almost as good builders as Chuch Norris. xD

**Comment by Gerydos** [comment]
**Update:** Any kind of building kills the game.

**Update2:** I loaded up the last save before I updated to 0.2.0.1 and the stas were fine. And after the update the stats increased like crazy.

**Comment by Barry-2707** [comment]
I have the same thing if you wait a few minutes in my save the game crashes with this specific crashlog.
[ToMuchProduction.2.zip](https://github.com/WarpzoneStudios/Hammerting/files/5976015/ToMuchProduction.2.zip)

**Comment by Gerydos** [comment]
**Callstack**

---------------------------
tdtd: The game has crashed.
---------------------------
Error: 

Hammerting version 0.2.0.3
Save version: version 0.2.0.0,version 0.2.0.1,version 0.2.0.3

Callstack:
0: fixed_point_cast<fixedpoint<int,16>,fixedpoint<__int64,16> >
core\fixedpoint.h:176:71
1: add_experience
tdtd\gamestate\public\gamestate\xp_level.h:226:14
2: add_experience_and_announce
tdtd\gamestate\public\gamestate\xp_level.h:288:0
3: event_callback_anim
tdtd\gamestate\behavior_trees\node_produce.cpp:117:0
4: event_component_system_trigger_event_hash_internal
entity\systems\event_component_system.cpp:343:15
5: event_component_system_trigger_event_hash
entity\systems\event_component_system.cpp:387:0
6: game_animation_system_update
tdtd\gamestate\systems\game_animation_system.cpp:437:0
7: entity_entity_manager_update
entity\entity_manager.cpp:183:0
8: gamestate::update
tdtd\gamestate\gamestate.cpp:626:0
9: main_main_h::update
tdtd\main\main.cpp:561:0
10: game_func
tdtd\main\main.cpp:917:0
11: thread_entry
wc_sys\thread.cpp:104:0
12: configthreadlocale
13: BaseThreadInitThunk
14: RtlUserThreadStart


Assertion failed: fp_from >= 0

File: C:\buildbot\build_tdtd-patch-windows-dev\warpcore\core\fixedpoint.h
Line: 176

We would love to see this error message, so we can have a chance to fix the problem. 

If you want to help us with this, please press CTRL+C to copy this text, then send it to bugs@warpzonestudios.com or join us on Discord and show us there: https://discord.gg/pbT9zhw


---------------------------
OK   
---------------------------
**Additional Comment**
It is the same save file loaded in game version 0.2.0.3

**Comment by fredrikz** [comment]
Fixed in 0.2.0.4
