### ISSUE TITLE
Broken AI: Dwarf doesn't stash his/her money from a Stone Bridge

### ISSUE THREAD

**Issue by Gerydos** [WarpzoneStudios/Hammerting#28]
**Describe the bug**
Dwars doesn't place their money into their dwelling if there is a Stone Bridge istead of any kind of floor block.

**To Reproduce**
1. Build a dwelling
2. Place down the Stone Bridge
3. Mine out the stone which was in the way(or it was inside the Stone Bridge), so the textures won't glitch.
4. Wait and see as your dwarfs greed goes up and they doesn't stash their money.

**Expected behavior**
Dwars being able to stash the coins. It was working perfectly in the stable version of the game.

**Screenshots**
![20210213135433_1](https://user-images.githubusercontent.com/78972553/107850484-19b23a00-6e03-11eb-8ee9-73cf3fb90642.jpg)

**Desktop (please complete the following information if pertinent):**
 - OS: Win 10 Pro
 - Sapphire R9 290
 - Game Version 0.2.0.0 and 0.2.0.1 and 0.2.0.2

**Additional context**
I've attached one of my saves so you doesn't have to wait and just load it and see it yourself.

**Save file:**
[savegame69.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/5975680/savegame69.2.save.zip)

**Comment by Srekel** [comment]
Aha, this is because the stone bridges are not aligned with the dwellings. The top row is, but not the bottom two rows. Dwarves need to be on equal height at the moment.

**Comment by Gerydos** [comment]
Oh god, yes. Now i see what is the problem. I didn't sat the last couple of buildings were not alogned.
THe rows are good, but the last bulding in the second row and the last 2 building in the last row was misaligned.

Sorry, didn't noticed it.
