### ISSUE TITLE
Graphics turn completely green after a few minutes and the game crashes shortly after.

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#32]
**Callstack (if a crash)**
![image](https://user-images.githubusercontent.com/78851197/107884195-dbe10e80-6ef3-11eb-9446-85786ddfb248.png)

**Describe the bug**
From a player
After a few minutes to an hour my game turns completely green and then crashes with the message above.
To close the game I have to use task manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/78851197/107884227-1cd92300-6ef4-11eb-9526-fd814e5453a8.png)

**Desktop (please complete the following information if pertinent):**
 
![image](https://user-images.githubusercontent.com/78851197/107884233-2793b800-6ef4-11eb-9946-a64d860640c2.png)

**Comment by Barry-2707** [comment]
It's on the stable 0.1.3.3 build

**Comment by Barry-2707** [comment]
Same user now posts on Discord that instead of his screen turning green it turns black. Instead of stable it is now on the Experimental bug. no crashreport this time.
https://discord.com/channels/346642400497762305/771649477601525763/813489830759628860

**Comment by WarpQueen** [comment]
This is a problem with the graphics card. It may need a new driver, or it is running too hot due to too weak or about to break. Not much we can do about it. In these cases, better tell them to send an e-mail to bugs@warpzonestudios.com and I can guide them through troubleshooting.
