### ISSUE TITLE
Unable to start Hammerting version 0.2.0.3

### ISSUE THREAD

**Issue by schmitzCatz** [WarpzoneStudios/Hammerting#33]
**Callstack (if a crash)**
---------------------------
Exception caught
---------------------------
Hammerting version 0.2.0.3
0:
ExceptionCode:
0xc0000005
ExceptionFlags:
0x0
ExceptionAddress:
0x7fff5f83e9da
Module:
C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.dll

Callstack:
0: vkQueueSubmit
1: <failed function lookup>
2: <failed function lookup>
3: <failed function lookup>
4: <failed function lookup>
5: <failed function lookup>
6: framegraph::create_swapchain
render\vk\framegraph.cpp:341:113
7: framegraph::create
render\vk\framegraph.cpp:82:0
8: render_render_device_register_renderpass
render\vk\device.cpp:789:0
9: gamegfx_register_renderpass
tdtd\media\gamegfx.cpp:3012:0
10: gfx_func
media\gfx.cpp:210:0
11: thread_entry
wc_sys\thread.cpp:104:0
12: configthreadlocale
13: BaseThreadInitThunk
14: RtlUserThreadStart

---------------------------
OK   
---------------------------

After renaming **SteamOverlayVulkanLayer64.dll** 

---------------------------
Exception caught
---------------------------
Hammerting version 0.2.0.3
0:
ExceptionCode:
0xc0000005
ExceptionFlags:
0x0
ExceptionAddress:
0x7ffefe771f98
Module:
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d67c20d727d4578c\nvoglv64.dll

Callstack:
0: vk_icdNegotiateLoaderICDInterfaceVersion
1: vkGetInstanceProcAddr
2: <failed function lookup>
3: <failed function lookup>
4: <failed function lookup>
5: <failed function lookup>
6: <failed function lookup>
7: framegraph::create_swapchain
render\vk\framegraph.cpp:341:113
8: framegraph::create
render\vk\framegraph.cpp:82:0
9: render_render_device_register_renderpass
render\vk\device.cpp:789:0
10: gamegfx_register_renderpass
tdtd\media\gamegfx.cpp:3012:0
11: gfx_func
media\gfx.cpp:210:0
12: thread_entry
wc_sys\thread.cpp:104:0
13: configthreadlocale
14: BaseThreadInitThunk
15: RtlUserThreadStart

---------------------------
OK   
---------------------------

**Describe the bug**
Unable to start Hammerting (Stable and Experimental)

**To Reproduce**
1. Go to Steam Library
2. Click on "Hammerting"
3. Click on "Play"

**Expected behavior**
Hope to play the game. :-)

**Screenshots**

**Desktop (please complete the following information if pertinent):**
 - OS: Windows 10 Professional 20H2 19042.804
 - Graphics Card: PNY GeForce RTX 3090 24GB XLR8 Gaming UPRISING EPIC-X (Driver Version: 8.1.960.0)
 - Game Version 0.2.0.3 and 0.1.4.19

**Additional context**
Disabled every Overlay Application and reinstalled the game several times. Unfortunately without any luck. Reinstalling display drivers did not help either.

**Comment by schmitzCatz** [comment]
Additional Information:
[DxDiag.txt](https://github.com/WarpzoneStudios/Hammerting/files/5983131/DxDiag.txt)
<img width="301" alt="2021-02-13 18_01_44-Exception caught" src="https://user-images.githubusercontent.com/10682393/107976941-a05d4780-6fba-11eb-92d3-dcf11a202fa1.png">
<img width="307" alt="2021-02-14 08_50_06-Exception caught" src="https://user-images.githubusercontent.com/10682393/107976948-a2bfa180-6fba-11eb-8208-42d038e15666.png">

**Comment by fredrikz** [comment]
Hi!

Thanks for the bug report.

Your DxDiag.txt looks OK.

It's good that you've tested to remove Steam overlay, to see that the error "moves" to Nvidias drivers instead. However, I believe it's not the Steam overlays fault, nor the Nvidia driver, but it's probably an overlay application you don't know about (this has been the case in all debug sessions I've had with this behavior). Known culprits:

- ReShade (unless you have the latest version)
- HUDSight
- ASUS GPU Tweak 2
- Mirillis ACTION!
- FPS Monitor
- <other programs with screen overlays and/or screen capture mechanics>

It's hard to track these programs however. Could you download https://vulkan.gpuinfo.org/download.php (version 3.0) and run it, save the file, and upload it here? It's like DxDiag, but for Vulkan.

![image](https://user-images.githubusercontent.com/67166/108040055-20c48c80-703d-11eb-8a94-545c13bc1581.png)

**Comment by schmitzCatz** [comment]
[GeForce RTX 3090.json.txt](https://github.com/WarpzoneStudios/Hammerting/files/5987420/GeForce.RTX.3090.json.txt)

Hi,

I did some further investigation, as soon as FPS Monitor is installed I get these crashes. Uninstalling did the trick. I'm wondering what the tool is doing even if it is not running.

Thanks!

**Comment by fredrikz** [comment]
The way FPS Monitor works is that it hooks into _every single process running Vulkan_. Which is not a good thing to do, if you also have crash bugs in the program.

People working with Vulkan are aware of the issue, and a "failsafe" mode is being considered: https://github.com/KhronosGroup/Vulkan-Loader/issues/513

I'm going to mail the FPS Monitor folks again, to see if they can fix the bug. If you feel like it, you could do the same (especially if you've paid for their product), since this crash could affect any application using Vulkan graphics

**Comment by fredrikz** [comment]
Closing this, as this is "yet another program hooking into Vulkan" issue.
