### ISSUE TITLE
Toncap mushrooms can't be used in medical recipe 

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#41]
Experimental Version 0.2.0.5
![изображение](https://user-images.githubusercontent.com/5548003/108241568-07b2fd00-715d-11eb-99b9-b40dd0e0ec47.png)
but 
![изображение](https://user-images.githubusercontent.com/5548003/108241602-10a3ce80-715d-11eb-8fd7-efeaf285f3a5.png)

**Comment by Gerydos** [comment]
It can not be used to make _Yeast_ in the _Cook House_.

![20210218123053_1](https://user-images.githubusercontent.com/78972553/108351034-41c7e180-71e5-11eb-9b20-f9732b06e9bf.jpg)

**Comment by jorbosaur** [comment]
Should be fixed now.
