### ISSUE TITLE
Remove dwelling 'roof'

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#45]
Dwelling 'roof' is rudiment and should be removed
![изображение](https://user-images.githubusercontent.com/5548003/108315189-21d7f400-71cc-11eb-9a62-6249cfff00ef.png)

**Additional context**
https://discord.com/channels/346642400497762305/723080599539286026/811638867932610591

**Comment by Makishima** [comment]
Same for cook house
![изображение](https://user-images.githubusercontent.com/5548003/108600365-f6116580-73a7-11eb-8fd3-f3844dcdf7ed.png)

**Comment by Srekel** [comment]
Fixed internally

**Comment by Srekel** [comment]
Fixed in 0.2.1.0

HAPPY NOW FREDRIK!?!?

**Comment by fredrikz** [comment]
> Fixed in 0.2.1.0
> 
> HAPPY NOW FREDRIK!?!?

💩💩💩💩💩
