### ISSUE TITLE
Dwarves will not complete quest, only delivering 9/10 but never completing it

### ISSUE THREAD

**Issue by fredrikz** [WarpzoneStudios/Hammerting#47]
**Describe the bug**
Dwarves will not complete quest, only delivering 9/10 but never completing it, even though there's nothing else to do

**Comment by fredrikz** [comment]
[9of10_questbug_save.zip](https://github.com/WarpzoneStudios/Hammerting/files/6000985/9of10_questbug_save.zip)

**Comment by Makishima** [comment]
Same for me
[delivery_quest_bug.zip](https://github.com/WarpzoneStudios/Hammerting/files/6004083/delivery_quest_bug.zip)

![изображение](https://user-images.githubusercontent.com/5548003/108382908-5d011400-721a-11eb-9e04-8b176015a208.png)

**Comment by Makishima** [comment]
Not only delivery for quest bugged
[bridge_bug.zip](https://github.com/WarpzoneStudios/Hammerting/files/6004698/bridge_bug.zip)

![изображение](https://user-images.githubusercontent.com/5548003/108396000-6a70cb00-7227-11eb-83ee-3f191e157f0d.png)

**Comment by Srekel** [comment]
Fixed in 0.2.0.10
