### ISSUE TITLE
Pathfinding bug

### ISSUE THREAD

**Issue by Barry-2707** [WarpzoneStudios/Hammerting#48]
**Describe the bug**
Sometimes dwarfs get stuck in a loop.

**Expected behavior**
Dwarfs should do their assigned task..

**Screenshots**
These are a few clips showing this issue.
[Hammerting.zip](https://github.com/WarpzoneStudios/Hammerting/files/6002550/Hammerting.zip)

**Desktop (please complete the following information if pertinent):**
 - OS: windows 10
 - Graphics Card gtx 970
 - Game Version 0.2.0.5

**Additional context**
Here is the log file corresponding to the bridges clip.
[2021-02-18_11-50-15_tdtd_YXEPIS.zip](https://github.com/WarpzoneStudios/Hammerting/files/6002559/2021-02-18_11-50-15_tdtd_YXEPIS.zip)

**Comment by Barry-2707** [comment]
Another example

https://discord.com/channels/346642400497762305/771649477601525763/811990760408744006

**Comment by Srekel** [comment]
The zip didn't work. Is this about the small scaffolding?

**Comment by Barry-2707** [comment]
Those clips are about abnormal behavior on both scaffolding, bridges and elevators. The clips are to large to zip apparently, will post them again in the #screenshots channel on discord.

**Comment by Srekel** [comment]
https://discord.com/channels/346642400497762305/590514596264017941/814074682974273566

**Comment by Srekel** [comment]
I think at least some of these may be fixed now, please open a new bug if you spot any new problems.
