### ISSUE TITLE
Toncap Mushroom can not be used for making Mushroom Swig

### ISSUE THREAD

**Issue by Gerydos** [WarpzoneStudios/Hammerting#54]
**Describe the bug**
Similiarly to an another issue [https://github.com/WarpzoneStudios/Hammerting/issues/41](https://github.com/WarpzoneStudios/Hammerting/issues/41) (which was solved with the latest 0.2.0.5 patch) toncap mushroom is not included in a recipe. 

**To Reproduce**
1. Build a Brewery
2. Try to make some Mushroom Swig and look for the Toncap Mushroom in the recipe
3. See error

**Expected behavior**
Toncap mushroom can be used to make Mushroom swig.

**Screenshots**
![20210219013612_1](https://user-images.githubusercontent.com/78972553/108504562-60e27400-72b6-11eb-8347-3b56bfcae155.jpg)

**Desktop (please complete the following information if pertinent):**
 - Game Version 0.2.0.5.

**Comment by Srekel** [comment]
Fixed in 0.2.1.0
