### ISSUE TITLE
Completed mission is not removed from list

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#65]
0.2.0.9
![изображение](https://user-images.githubusercontent.com/5548003/108726126-21c35580-7538-11eb-9245-e7a0fcce8609.png)

**Comment by Srekel** [comment]
Did you learn FL before "unlocking" the Cave mission?

**Comment by Makishima** [comment]
It is hard to say, I look into missions after I won the war, so maybe.

**Comment by ZapZockt** [comment]
I can confirm the problem:
![grafik](https://user-images.githubusercontent.com/78972579/109792274-a20e4880-7c13-11eb-9728-85b2d7073f05.png)

The quest popped up relatively late, long time after I did learn the skill.

**Comment by Srekel** [comment]
Fixed in 0.2.1.0
