### ISSUE TITLE
Allow to build on Cornerstone in edge cases

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#68]
If it is possible I would suggest slightly change #49 to allow build _on top_ of it
I found that the stairs and elevator station nicely fit on the cornerstone but cannot be built
![изображение](https://user-images.githubusercontent.com/5548003/108732872-00199c80-753f-11eb-993e-6b2a02680d45.png)
![изображение](https://user-images.githubusercontent.com/5548003/108732889-0576e700-753f-11eb-884d-53c558710080.png)

**Comment by Makishima** [comment]
Railway station too
![изображение](https://user-images.githubusercontent.com/5548003/108752491-94dac500-7554-11eb-907e-0ecc63e778a3.png)

**Comment by Makishima** [comment]
This one should be possible too if there is no issue for dwarf's pathing
![изображение](https://user-images.githubusercontent.com/5548003/108874787-8bf9fa00-760d-11eb-9625-0ca0143c1e1b.png)

**Comment by Srekel** [comment]
I'm going to close this, it feels a bit too edge casey (rare) for the work/risk required (it's a... sensitive system)
