### ISSUE TITLE
Ancient Dwarf Statues spawn in blocks

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#70]
Most statues in my game spawn like that.
![изображение](https://user-images.githubusercontent.com/5548003/108816246-e1f77f00-75c6-11eb-8c3b-f88f0f85b276.png)

**Comment by jorbosaur** [comment]
Not sure I mind that archeology can spawn somewhat buried, but I nevertheless increased its digout footprint. Shouldn't happen now.
