### ISSUE TITLE
Items in front of Caves can't be picked up without attacking the cave

### ISSUE THREAD

**Issue by ZapZockt** [WarpzoneStudios/Hammerting#79]
**Describe the solution you'd like**
If an item, that is normally pickable, like an ore lore or campfire was placed in front of a monster cave, you can not mark it for pickup. Instead, an attack order is given.

**Describe the bug**
The pickup items should be pickable although the cave is not yet destroyed

**To Reproduce**
search for a cave, that has some pickup items in front, like in the screenshot below. Try to mark them for pickup, an attack order will be given instead of a pickup order. I assume the Z-order is incorrect, setting the cave in front of the items, although the real order is the other way round.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78972579/109801026-38476c00-7c1e-11eb-8780-77df377377cd.png)

**Desktop (please complete the following information if pertinent):**
 - Game Version : latest experimental

**Comment by Srekel** [comment]
Fixed in 0.2.1.0 :)
