### ISSUE TITLE
Assertion failed: fp_from >= 0

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#82]
Set order to craft 2 axes and some dig behind the scaffold

[2021-03-04_19-55-30_tdtd_YQOZYZ.zip](https://github.com/WarpzoneStudios/Hammerting/files/6085560/2021-03-04_19-55-30_tdtd_YQOZYZ.zip)

<details>
<summary>Details</summary>
Error: 

Hammerting version 0.2.1.0

Additional assert messages:
Entity: 947, parent: 0, may_change_target: 1, has_queued_target: 1, should_update_target: 1, should_exit_bt: 0, different_prev_pos: 0, target_invalid: 1

Callstack:
0: fixed_point_cast<fixedpoint<int,16>,fixedpoint<__int64,16> >
core\fixedpoint.h:176:71
1: fixedpoint<int,16>::cast<fixedpoint<__int64,16> >
core\fixedpoint.h:197:11
2: bt_walk_enter
tdtd\gamestate\behavior_trees\node_walk.cpp:52:63
3: movement_behavior_update
tdtd\gamestate\systems\movement_system.cpp:961:0
4: movement_system_update
tdtd\gamestate\systems\movement_system.cpp:1071:0
5: entity_entity_manager_update
entity\entity_manager.cpp:183:0
6: gamestate::update
tdtd\gamestate\gamestate.cpp:625:0
7: main_main_h::update
tdtd\main\main.cpp:561:0
8: game_func
tdtd\main\main.cpp:921:0
9: thread_entry
wc_sys\thread.cpp:104:0
10: configthreadlocale
11: BaseThreadInitThunk
12: RtlUserThreadStart

Assertion failed: fp_from >= 0

File: C:\buildbot\build_tdtd-patch-windows-dev\warpcore\core\fixedpoint.h
Line: 176

We would love to see this error message, so we can have a chance to fix the problem. 

If you want to help us with this, please press CTRL+C to copy this text, then send it to bugs@warpzonestudios.com or join us on Discord and show us there: https://discord.gg/pbT9zhw

---------------------------
OK   
---------------------------

</details>

**Comment by Srekel** [comment]
Fixed in 0.2.1.1
