### ISSUE TITLE
Dwarfs can set themselves into the trap in stonebridge

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#87]
Sometimes they fall into bridges or build them over themselves, not sure

[6.2.save.zip](https://github.com/WarpzoneStudios/Hammerting/files/6091025/6.2.save.zip)

![изображение](https://user-images.githubusercontent.com/5548003/110127123-4809b080-7dd6-11eb-84ab-1d505a02b6e4.png)
![изображение](https://user-images.githubusercontent.com/5548003/110127102-4213cf80-7dd6-11eb-8499-e63e68b33dd0.png)

**Comment by Makishima** [comment]
yep, they fall into bridges
this one is trapped after he mine block next to him
![изображение](https://user-images.githubusercontent.com/5548003/110127467-bcdcea80-7dd6-11eb-9d6d-a622ea0b6308.png)

**Comment by smokingwreckage** [comment]
Have seen them build the bridge on themselves, become totally paralyzed - can't even unbuild the bridge themselves.

**Comment by Srekel** [comment]
Fixed in 0.2.1.7
