### ISSUE TITLE
Quarry model is overlapping building under it

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#88]
![изображение](https://user-images.githubusercontent.com/5548003/110133480-67f0a280-7ddd-11eb-8570-45e4dc46ecfb.png)

**Comment by Makishima** [comment]
Destroyed door too
![изображение](https://user-images.githubusercontent.com/5548003/110145575-a3459e00-7dea-11eb-8c90-8fb4737f7c83.png)

**Comment by fredrikz** [comment]
Fixed in 0.2.1.4
