### ISSUE TITLE
Dwarves should not attack lairs unless told to

### ISSUE THREAD

**Issue by WarpQueen** [WarpzoneStudios/Hammerting#9]
From player: https://steamcommunity.com/app/760650/discussions/0/3112519747616487942/

**Is your feature request related to a problem? Please describe.**
Dwarves seem to target the dens (monster spawners) without being told to. What if we want to leave the den active and kill off the spawns for materials? Having a hard time getting any rat pelt since i was forced to destroy the rat den near spawn. 

**Describe the solution you'd like**
Just that they should not attack lairs unless ordered to.

**Comment by Srekel** [comment]
Fixed somewhere around 0.2.0.9
