### ISSUE TITLE
Locomotion_system_update

### ISSUE THREAD

**Issue by ZapZockt** [WarpzoneStudios/Hammerting#95]
**Callstack (if a crash)**
---------------------------
Exception caught
---------------------------
Hammerting version 0.2.1.5
0:
ExceptionCode:
0xc0000094
ExceptionFlags:
0x0
ExceptionAddress:
0x7ff8da44facd
Module:
R:\SteamLibrary\steamapps\common\Hammerting\game.x86_64.dll

Callstack:
0: locomotion_system_update
tdtd\gamestate\systems\locomotion_system.cpp:260:7
1: entity_entity_manager_update
entity\entity_manager.cpp:183:0
2: gamestate::update
tdtd\gamestate\gamestate.cpp:634:0
3: main_main_h::update
tdtd\main\main.cpp:561:0
4: game_func
tdtd\main\main.cpp:935:0
5: thread_entry
wc_sys\thread.cpp:104:0
6: configthreadlocale
7: BaseThreadInitThunk
8: RtlUserThreadStart

**Describe the bug**
Started new game with 0.2.1.5, played 10min with 2x speed, had several buildsites planed, and suddenly this happened

**To Reproduce**
not sure, how to reproduce, there was no specific event happening, that was obvious for me

**Expected behavior**
don't crash

**Screenshots**
Here you can see everything, that was made since the start
![grafik](https://user-images.githubusercontent.com/78972579/111021052-21490c80-83ca-11eb-83b3-57c5e3320967.png)

**Comment by Srekel** [comment]
Fixed in 0.2.1.6
