### ISSUE TITLE
Pathfinding: Elevator Station buildsite makes everything around "not reachable"

### ISSUE THREAD

**Issue by ZapZockt** [WarpzoneStudios/Hammerting#97]
**Describe the bug**
I had two quarries, both were working fine, they are connected to the dungeon by a scaffold, and some bridges, were reachable all the time. Then I build an elevator station between the two and both quarries got instantly marked as "No dwarf can get here", although they are both logically reachable.

You can see the situation in the screenshot below. The left quarry is absolutely 100% connected to the dungeon. For the right, one could maybe say that the buildsite for the station could be blocking the access, but dwarfs run from left to right to deliver other build sites so in general, it is not "unreachable".

**To Reproduce**
See the screenshot below and try to build anything as I did and place an elevator station between the existing buildings

**Expected behavior**
The pathfinding should be able to reach both buildings, although the elevator buildsite is next to them.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78972579/111057391-7d259b00-8487-11eb-803e-9cb75055570a.png)

Edit:
funny observation: One level below it was almost the same situation, beside the fact, that the station was the bottom one, but the buildings there were still reachable:
![grafik](https://user-images.githubusercontent.com/78972579/111057438-da215100-8487-11eb-9781-6aec77fe73c7.png)

**Desktop (please complete the following information if pertinent):**
 - Game Version 0.2.1.6 experimental

**Comment by ZapZockt** [comment]
Edit:

it seems there is something different going on. I built a third quarry, to work around the problem. Directly after building the quarry, all was fine:

![grafik](https://user-images.githubusercontent.com/78972579/111057891-fe326180-848a-11eb-82f7-d9df894f425e.png)

When I add a few stones to the todo-list, the game suddenly says, the quarry is not reachable:

![grafik](https://user-images.githubusercontent.com/78972579/111057918-346fe100-848b-11eb-9a0d-9f6d485e6314.png)

This makes not much sense, does it?

**Comment by Srekel** [comment]
Fixed in 0.2.1.8 with an improved tooltip:
![image](https://user-images.githubusercontent.com/1578924/111285013-003e2100-8641-11eb-9de7-34702b1c3fbc.png)

**Comment by ZapZockt** [comment]
But what is causing this? There are dwarfs, that are able to do the job and the path should be usable. I can see no reason, why the dwarfs who can do the job, do not find their way?

**Comment by Srekel** [comment]
Your only allowed stone masons are these two guys:
![image](https://user-images.githubusercontent.com/1578924/111290010-fff45480-8645-11eb-8c82-8112ca4ab041.png)

They are both stuck here:

![image](https://user-images.githubusercontent.com/1578924/111290089-169aab80-8646-11eb-926f-73133c8bc437.png)

**Comment by ZapZockt** [comment]
LoL, okay 👯‍♂️

**Comment by Srekel** [comment]
FYI, they are also marked as "Stranded" :)

If it's any consolation, I spent a good while trying to figure this out as well....
