### ISSUE TITLE
"Can't do" icons is not clickable in whole area

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#99]
0.2.1.6
Icons such 
![изображение](https://user-images.githubusercontent.com/5548003/111062259-d528c580-84b8-11eb-9f9a-447f05aaba8c.png) or ![изображение](https://user-images.githubusercontent.com/5548003/111062264-da861000-84b8-11eb-9847-d9e59f5a550b.png), ect, is only clickable on 'action' part but I can't click on 🚫

**Comment by Srekel** [comment]
Fixed in 0.2.1.7
